Documentation:
    Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 121

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - splitclient-rb.gemspec

Naming/FileName:
  Exclude:
    - splitclient-rb.gemspec

AllCops:
  TargetRubyVersion: 2.3.6
  Exclude:
    - gemfiles/* # excluded as appraisal generates them with errors
    - lib/*
    - lib/murmurhash/**/*
    - lib/splitclient-rb/*
    - lib/splitclient-rb/cache/adapters/**/*
    - lib/splitclient-rb/cache/repositories/**/*
    - lib/splitclient-rb/cache/routers/**/*
    - lib/splitclient-rb/cache/senders/**/*
    - lib/splitclient-rb/cache/stores/sdk_blocker.rb
    - lib/splitclient-rb/cache/stores/segment_store.rb # ABC for segments_thread is 15.17/15
    - lib/splitclient-rb/cache/stores/split_store.rb
    - lib/splitclient-rb/clients/**/*
    - lib/splitclient-rb/managers/**/*
    - lib/splitclient-rb/engine/api/**/*
    - lib/splitclient-rb/engine/models/**/*
    - lib/splitclient-rb/engine/parser/condition.rb
    - lib/splitclient-rb/engine/parser/evaluator.rb
    - lib/splitclient-rb/engine/parser/split_adapter.rb
